# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmCnSVVJ-vgFNXL1Wz6r3-I4U9LdYvq9
"""

import streamlit as st

st.title("✅ App is working")
st.write("If you see this → Streamlit is OK")
