# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmCnSVVJ-vgFNXL1Wz6r3-I4U9LdYvq9
"""

import streamlit as st
from chatbot import handle_user_input

st.set_page_config(
    page_title="TravelBot",
    page_icon="🌍",
    layout="wide"
)

st.title("🌍 TravelBot")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    st.write(msg["role"] + ": " + msg["content"])

user_input = st.chat_input("Type something...")

if user_input:

    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.spinner("Thinking..."):

        response = handle_user_input(user_input)

    st.session_state.messages.append({"role": "bot", "content": response})

    st.write("Bot:", response)
