# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmCnSVVJ-vgFNXL1Wz6r3-I4U9LdYvq9
"""

import streamlit as st
from chatbot import handle_user_input

# ============================================
# PAGE CONFIG
# ============================================

st.set_page_config(
    page_title="TravelBot",
    page_icon="🌍",
    layout="wide"
)

# ============================================
# CUSTOM CSS
# ============================================

st.markdown("""
<style>

.main {
    background-color: #0E1117;
}

.stChatMessage {
    padding: 12px;
    border-radius: 15px;
    margin-bottom: 10px;
}

h1 {
    text-align: center;
    color: white;
    font-size: 50px;
}

.subtitle {
    text-align: center;
    color: #A0A0A0;
    margin-bottom: 30px;
    font-size: 18px;
}

.user-msg {
    background-color: #2563EB;
    padding: 12px;
    border-radius: 12px;
    color: white;
}

.bot-msg {
    background-color: #1F2937;
    padding: 12px;
    border-radius: 12px;
    color: white;
}

.footer {
    text-align: center;
    color: gray;
    margin-top: 30px;
}

</style>
""", unsafe_allow_html=True)

# ============================================
# TITLE
# ============================================

st.markdown("<h1>🌍 TravelBot</h1>", unsafe_allow_html=True)

st.markdown(
    "<p class='subtitle'>AI Travel Assistant powered by Qwen</p>",
    unsafe_allow_html=True
)

# ============================================
# SESSION STATE
# ============================================

if "messages" not in st.session_state:
    st.session_state.messages = []

# ============================================
# SIDEBAR
# ============================================

with st.sidebar:

    st.title("⚙️ Settings")

    st.markdown("---")

    st.write("### Features")
    st.write("✅ Trip Planning")
    st.write("✅ Weather")
    st.write("✅ AI Chat")

    st.markdown("---")

    if st.button("🗑️ Clear Chat"):

        st.session_state.messages = []

        st.rerun()

# ============================================
# DISPLAY CHAT HISTORY
# ============================================

for message in st.session_state.messages:

    if message["role"] == "user":

        st.markdown(
            f"""
            <div class="user-msg">
            👤 <b>You:</b><br>
            {message["content"]}
            </div>
            """,
            unsafe_allow_html=True
        )

    else:

        st.markdown(
            f"""
            <div class="bot-msg">
            🤖 <b>TravelBot:</b><br>
            {message["content"]}
            </div>
            """,
            unsafe_allow_html=True
        )

# ============================================
# CHAT INPUT
# ============================================

user_input = st.chat_input("Type your destination...")

# ============================================
# HANDLE INPUT
# ============================================

if user_input:

    # Save user message
    st.session_state.messages.append(
        {
            "role": "user",
            "content": user_input
        }
    )

    # Display user message
    st.markdown(
        f"""
        <div class="user-msg">
        👤 <b>You:</b><br>
        {user_input}
        </div>
        """,
        unsafe_allow_html=True
    )

    # Generate response
    with st.spinner("✈️ Planning your trip..."):

        response = handle_user_input(user_input)

    # Save bot response
    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": response
        }
    )

    # Display bot response
    st.markdown(
        f"""
        <div class="bot-msg">
        🤖 <b>TravelBot:</b><br>
        {response}
        </div>
        """,
        unsafe_allow_html=True
    )

# ============================================
# FOOTER
# ============================================

st.markdown(
    """
    <div class="footer">
    Made with ❤️ using Streamlit & Qwen
    </div>
    """,
    unsafe_allow_html=True
)