# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnxQy9mAHFSH--V3uBMEnjn0OWR2Z-ze
"""

import streamlit as st
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import requests

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"


tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

"""**Memory System**"""

conversation_history = []
user_profile = {"name": None}
bot_state = {"waiting_for": None, "city": None}

def add_to_memory(role, content):
    conversation_history.append({"role": role, "content": content})

def get_memory_as_prompt():
    prompt = "<|system|>\nYou are TravelBot, a friendly travel assistant. Help users plan trips and suggest destinations. Be concise.\n"
    for message in conversation_history[-10:]:
        if message["role"] == "user":
            prompt += f"<|user|>\n{message['content']}\n"
        else:
            prompt += f"<|assistant|>\n{message['content']}\n"
    prompt += "<|assistant|>\n"
    return prompt

"""**Weather Feature**"""

def get_weather(city):
    try:
        url = f"https://wttr.in/{city}?format=3"
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            return f" {response.text.strip()}"
        return None
    except:
        return None

def extract_city(text):
    cities = ["paris", "london", "dubai", "cairo", "tokyo",
              "rome", "barcelona", "istanbul", "bangkok", "amsterdam",
              "new york", "sydney", "singapore", "berlin", "madrid"]
    for city in cities:
        if city in text.lower():
            return city.title()
    return None

"""**Trip Planner Feature**"""

def build_trip_prompt(user_message):
    return f"""<|system|>
You are TravelBot, an expert trip planner. Create a detailed day-by-day itinerary.
Include: places to visit, local food, and travel tips. Be specific and helpful.
<|user|>
{user_message}
<|assistant|>
"""

"""**Core Chat Function**"""

def chat(model, tokenizer, prompt):
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids
    input_ids = input_ids.to(next(model.parameters()).device)

    generated_output = model.generate(
        input_ids,
        max_new_tokens=300,
        do_sample=True,
        temperature=0.7,
        pad_token_id=tokenizer.eos_token_id,
        attention_mask=input_ids.ne(tokenizer.pad_token_id)
    )

    full_text = tokenizer.decode(generated_output[0], skip_special_tokens=True)

    if "<think>" in full_text:
        full_text = full_text.split("</think>")[-1].strip()

    if "<|assistant|>" in full_text:
        return full_text.split("<|assistant|>")[-1].strip()
    return full_text.strip()

"""**Smart Response Handler**"""

def handle_user_input(user_message):

    # ✅ Goodbye detection
    goodbyes = ["bye", "goodbye", "thanks", "thank you", "done", "exit", "that's all"]
    if any(g in user_message.lower() for g in goodbyes):
        name_part = f" {user_profile['name']}" if user_profile["name"] else ""
        cities_visited = [m["content"] for m in conversation_history if "plan a trip" in m["content"]]
        if cities_visited:
            cities = ", ".join([c.replace("plan a trip to ", "") for c in cities_visited])
            return (f"✈️ Safe travels{name_part}!\n"
                    f"📍 Cities you explored: {cities}\n"
                    f"Have an amazing trip! See you soon 🌍")
        return f"✈️ Safe travels{name_part}! See you soon 🌍"

    # Save name if mentioned
    if "my name is" in user_message.lower():
        name = user_message.lower().split("my name is")[-1].strip().split()[0].title()
        user_profile["name"] = name

    # Greeting
    greetings = ["hello", "hi", "hey", "salam", "marhaba"]
    if any(g in user_message.lower() for g in greetings):
        name_part = f", {user_profile['name']}" if user_profile["name"] else ""
        bot_state["waiting_for"] = "city"
        return f"👋 Hello{name_part}! I'm TravelBot 🌍\nWhere do you want to go?"

    # ✅ State 1: مستني اسم المدينة
    if bot_state["waiting_for"] == "city":
        city = extract_city(user_message)
        if city:
            bot_state["city"] = city
            bot_state["waiting_for"] = "action"
            return (f"Great choice! ✈️ {city}\n\n"
                    f"What do you want?\n"
                    f"1️⃣ Trip Plan\n"
                    f"2️⃣ Weather\n"
                    f"3️⃣ Both")
        else:
            return "I didn't recognize that city 😅\nTry: Paris, Tokyo, Dubai, Cairo, London..."

    # ✅ State 2: مستني الاختيار
    if bot_state["waiting_for"] == "action":
        city = bot_state["city"]
        msg = user_message.lower()

        # Weather فقط
        if msg in ["2", "weather"]:
            bot_state["waiting_for"] = "city"
            bot_state["city"] = None
            weather = get_weather(city)
            if weather:
                return f"{weather}\n\n🌍 Want to explore another city? Where to next?"
            return f"Sorry, couldn't get weather for {city} 😅\n\n🌍 Try another city?"

        # Trip Plan فقط
        if msg in ["1", "trip", "plan"]:
            bot_state["waiting_for"] = "want_weather"
            print(f"TravelBot: ⏳ Planning your trip to {city}...\n")
            prompt = build_trip_prompt(f"Plan a 3 day trip to {city}")
            response = chat(model, tokenizer, prompt)
            add_to_memory("user", f"plan a trip to {city}")
            add_to_memory("assistant", response)
            return f"{response}\n\n🌤️ Want weather for {city} too? (yes / no)"

        # Both
        if msg in ["3", "both"]:
            bot_state["waiting_for"] = "city"
            bot_state["city"] = None
            print(f"TravelBot: ⏳ Planning your trip to {city}...\n")
            prompt = build_trip_prompt(f"Plan a 3 day trip to {city}")
            response = chat(model, tokenizer, prompt)
            weather = get_weather(city)
            add_to_memory("user", f"plan a trip to {city}")
            add_to_memory("assistant", response)
            return (f"{response}\n\n"
                    f"{weather}\n\n"
                    f"🌍 Want to explore another city? Where to next?")

        return "Please choose:\n1️⃣ Trip Plan\n2️⃣ Weather\n3️⃣ Both"

    # ✅ State 3: بعد الـ Trip Plan يسأل عن الجو
    if bot_state["waiting_for"] == "want_weather":
        city = bot_state["city"]
        msg = user_message.lower()

        if "yes" in msg or msg == "y":
            bot_state["waiting_for"] = "city"
            bot_state["city"] = None
            weather = get_weather(city)
            if weather:
                return f"{weather}\n\n🌍 Want to explore another city? Where to next?"
            return f"Sorry, couldn't get weather 😅\n\n🌍 Where to next?"

        else:
            bot_state["waiting_for"] = "city"
            bot_state["city"] = None
            return "🌍 Want to explore another city? Where to next?"

    # General conversation with memory
    add_to_memory("user", user_message)
    prompt = get_memory_as_prompt()
    response = chat(model, tokenizer, prompt)
    add_to_memory("assistant", response)
    return response

